language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"

env:
    - DJANGO_VERSION=1.5

install:
    - pip install tox
    - pip install python-coveralls

script:
    - tox -e py${TRAVIS_PYTHON_VERSION/./}-${DJANGO_VERSION}

after_success:
  - coveralls
